# Make sure that the ingress gateway has port 8080 open
# otherwise, this gateway will not work.
# gateway selector matches by labels regardless which
# namespace the actual ingress gateway might have been
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: helloworld-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http2
      protocol: HTTP
    hosts:
    - "*us-south.lb.appdomain.cloud"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
  - "*us-south.lb.appdomain.cloud"
  gateways:
  - helloworld-gateway
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: helloworld
        subset: v2
        port:
          number: 5000
      weight: 50
    - destination:
        host: helloworld
        subset: v1
        port:
          number: 5000
      weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld-destination-dr
spec:
  host: helloworld.sample.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2